######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 11 19:16:26 2013
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
SOURCES += AddPlayerDialog.cpp
SOURCES += MainWindow.cpp
SOURCES += Game.h

HEADERS += AddPlayerDialog.h
HEADERS += MainWindow.h
HEADERS *= Game.h
